### ISSUE TITLE
Question - What am I doing wrong

### ISSUE THREAD

**Issue by mrjrt** [alastairtree/LazyCache#140]
I just realised our unit tests in a library weren't passing, and the cause seems to be the jump from LazyCache.AspNetCore 2.0.1 to anything higher. I've looked at the diffs and I can't for the life of me see why it would fail on newer versions, so some insight would be appreciated. 

Code is basically pretty simple...

In the unit test:
```
var dependency = Mock.Of<IDependency>();
var cache = Create.MockedCachingService();
var service = new Service(dependency.Object, cache);
var res = service.DoSomething("arg");
```

In Service.cs:
```
var cacheKey = $"{typeof(Service).FullName}-arg-{arg}";
var result = _cache.GetOrAdd(cacheKey, () => dependency.DoActualThing(arg, CancellationToken.None), TimeSpan.FromHours(24));

```
...and what I get on that last line is:
```
System.ArgumentException
  HResult=0x80070057
  Message=Object of type 'LazyCache.Testing.Common.CacheEntryFake' cannot be converted to type 'Microsoft.Extensions.Caching.Memory.ICacheEntry'.
  Source=System.Private.CoreLib
  StackTrace:
   at System.RuntimeType.TryChangeType(Object value, Binder binder, CultureInfo culture, Boolean needsSpecialCast)
   at System.RuntimeType.CheckValue(Object value, Binder binder, CultureInfo culture, BindingFlags invokeAttr)
   at System.Reflection.MethodBase.CheckArguments(Object[] parameters, Binder binder, BindingFlags invokeAttr, CultureInfo culture, Signature sig)
   at System.Reflection.RuntimeMethodInfo.InvokeArgumentsCheck(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at LazyCache.Testing.Moq.NoSetUpDefaultValueProvider.GetDefaultValue(Type type, Mock mock)
   at Moq.DefaultValueProvider.GetDefaultReturnValue(MethodInfo method, Mock mock)
   at Moq.Mock.GetDefaultValue(MethodInfo method, Mock& candidateInnerMock, DefaultValueProvider useAlternateProvider)
   at Moq.Behaviors.ReturnBaseOrDefaultValue.Execute(Invocation invocation)
   at Moq.Return.Handle(Invocation invocation, Mock mock)
   at Moq.Mock.Moq.IInterceptor.Intercept(Invocation invocation)
   at Moq.CastleProxyFactory.Interceptor.Intercept(IInvocation underlying)
   at Castle.DynamicProxy.AbstractInvocation.Proceed()
   at Castle.Proxies.IAppCacheProxy.GetOrAdd[T](String key, Func`2 addItemFactory, MemoryCacheEntryOptions policy)
   at LazyCache.AppCacheExtensions.GetOrAdd[T](IAppCache cache, String key, Func`1 addItemFactory, MemoryCacheEntryOptions policy)
   at LazyCache.AppCacheExtensions.GetOrAdd[T](IAppCache cache, String key, Func`1 addItemFactory, TimeSpan slidingExpiration)
...etc
```

...and that works fine on v2.0.1 of LazyCache.AspNetCore. What am I missing?

**Comment by alastairtree** [comment]
I think you Mock might be calling/using an IAppCache extension method. How about using [the Mock that ships with LazyCache instead](https://github.com/alastairtree/LazyCache/blob/master/LazyCache/Mocks/MockCachingService.cs)?

**Comment by alastairtree** [comment]
Will close as no response, but we can re-open if required. Thanks.
