### ISSUE TITLE
LazyCache Works on Localhost but Not on Remote IIS Server

### ISSUE THREAD

**Issue by PostAlmostAnything** [alastairtree/LazyCache#146]
I have LazyCache working on an ASP.Net 4.7.2 WebForms site. It works just fine on localhost but when I upload it to the server I never seem to see cached results. I use it to cache table adapter objects. One of them should be refreshed every 30 minutes and it is on localhost, but after uploading it to the remote IIS 10 server I always see fresh results. 

What might cause an IIS server to not run LazyCache properly?

**Comment by alastairtree** [comment]
Without code or specific details it will be very hard to know. Are there any exceptions being raised? Are there any differences in deployment between the two environments? Configuration differences? 
Try adding some diagnostic logging to the app to help diagnose when something is being cached and with what key, when the cache item is actually being generated etc.
I would suspect it will be something else other than LazyCache that is causing the difference in behaviour.

**Comment by PostAlmostAnything** [comment]
Thanks for your time. I have the same suspicions about configuration differences. How do you recommend logging when something is added to the cache? I just added the Nuget package and then I cache table adapter objects like so:

` public Posts.GetPostsPagedDataTable GetPostsByTagPaged(int startRowIndex, int maximumRows, string hashtag, string search)
    {
        IAppCache cache = new CachingService(CachingService.DefaultCacheProvider) { DefaultCachePolicy = new CacheDefaults { DefaultCacheDurationSeconds = GlobalStatic.SITEPOSTSCACHEDURATION() } };
        string cacheKey = GlobalStatic.SITEGETPOSTSBYTAGCACHEKEY();
        Func<Posts.GetPostsPagedDataTable> actionThatWeWantToCache = () => Adapter.GetPostsByTagPaged(startRowIndex, maximumRows, hashtag, search);
        var CachedAdapter = cache.GetOrAdd(cacheKey, actionThatWeWantToCache);
        return CachedAdapter;
    }`

**Comment by PostAlmostAnything** [comment]
I forgot to mention that the configuration differences are that on localhost I am using the default instance of IIS Express created by Visual Studio 2019. On the server I am using IIS 10 running on Windows Server 2019.

I have checked the memory settings in IIS and didn't see anything that would explain why LazyCache does not work. I have the application pool set to AlwaysRunning and the private memory limit is much larges than should be necessary to cache this data. Is there anything that must be done in IIS to make LazyCache work beyond the instructions you've provided?

I am new to caching and don't know if there is something IIS requires that you don't cover in your installation instruction. I simply installed the Nuget package, configured it, got it working on my desktop, and uploaded it to the server.

**Comment by alastairtree** [comment]
It is very unlikely to be server config or IIS edition related. Much more likely to be your code or you application config.
I can see a few possible issues in that code:

* What value does `GlobalStatic.SITEPOSTSCACHEDURATION()` have? Ensure it is actually being cached for the correct time while running in production.
* You are using the same cache key for all invocations of that method. If I first search for rows 1-10 matching "ant" then the search results for "ant" are placed in the cache. Later when I search for rows 11-20 of "bat" the first 10 rows for ant will be returned from the cache because I am using the same key for both queries. Each set of query params needs a unique key.
`string cacheKey = $"GetPostsByTagPaged_{startRowIndex}_{maximumRows}_{hashtag}_{search}";`
* Suggest you [add some logging](https://docs.microsoft.com/en-us/dotnet/core/extensions/logging) to help understand what is going on:
```
Func<Posts.GetPostsPagedDataTable> actionThatWeWantToCache = () => {
  _logger.LogInformation("Saving GetPostsPagedDataTable to cache with key " + cacheKey + " for duration " + GlobalStatic.SITEPOSTSCACHEDURATION() + "s.");
  return Adapter.GetPostsByTagPaged(startRowIndex, maximumRows, hashtag, search);
}
       
```
(In general this sort of query is likely to get more support on StackOverflow than here - much more people read support questions like this over there rather than here)

**Comment by PostAlmostAnything** [comment]
To answer your question GlobalStatic.SITEPOSTSCACHEDURATION() is set like this
`public static int SITEPOSTSCACHEDURATION()
    {
        return 86400;
    }`
Do you have a logging example for a webforms? The link you gave me is for .Net Core. 

I thought the same thing about using the same cache key for different things, but when I tested it out on my development machine it worked fine. My understanding of the getoradd() function is that it checks to see if changes were made before deciding whether to get something from the cache or adding something new. It never caused the same results to be rendered for different tags. I'll try using a unique key for each parameter.

**Comment by PostAlmostAnything** [comment]
Could there a possible conflict with LazyCache and other caching methods in the application? I have some objectdatasource controls with caching enabled set to true.

**Comment by alastairtree** [comment]
Sorry for the slow reply. Did you manage to fix? I very much doubt it is a conflict, I think the issue will be in your code, in particular you must ensure each thing is cached with it's own key. Or perhaps the deployment is not deploying everything you think?
Something like Log4Net is a good logging library in full framework, perhaps look at that as i think you need to add more diagnostic code to understand the problem better.
If you are still struggling I suggest you setup a quick hello world app and add caching to that to reproduce the issue and then share the code for the app.

**Comment by bradleykronson** [comment]
I'm seeing the same thing - seeing the following error in my Logs

This is when the data is returned from the lookup function

System.Exception: MethodNotAllowed Method Not Allowed

   at DSTV.Unification.Web.DStv.TvGuide.TvGuideRepository.<>c__DisplayClass7_0.<GetProgrammes>g__Data|0() in C:\Sites\www\dstv-unification\site\DSTV.Unification.Web\DStv\TvGuide\TvGuideRepository.cs:line 145
   at LazyCache.CachingService.<>c__DisplayClass21_1`1.<GetOrAdd>b__1()
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at LazyCache.CachingService.GetValueFromLazy[T](Object item, Boolean& valueHasChangedType)
   at LazyCache.CachingService.GetOrAdd[T](String key, Func`2 addItemFactory, MemoryCacheEntryOptions policy)

**Comment by alastairtree** [comment]
Closing as inactive.
